pipeline{
    agent any
    environment {
        PATH = "$PATH:/opt/apache-maven-3.0.5/bin"
    }
    stages{
       stage('GetCode'){
            steps{
                git 'https://https://github.com/kirantonny/DevOps/blob/master/sonarqube/Jenkinsfile'
            }
         }        
       stage('Build'){
            steps{
                sh 'mvn clean package'
            }
         }
        stage('SonarQube analysis') {
//    def scannerHome = tool 'SonarScanner ';
        steps{
        withSonarQubeEnv('sonarqube-7.9.1') { 
        // If you have configured more than one global server connection, you can specify its name
//      sh "${scannerHome}/bin/sonar-scanner"
        sh "mvn sonar:sonar"
    }
        }
        }
       
    }
}
